version: '3.9'

services:
  churn-fastapi:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: churn-fastapi
    ports:
      - "8000:8000"
    command: ["uvicorn", "src.inference.app:app", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - ./src:/app/src
      - ./requirements.txt:/app/requirements.txt

  churn-gradio:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: churn-gradio
    ports:
      - "7860:7860"
    environment:
      - ENV_MODE=docker  # <<< THIS IS IMPORTANT
    command: ["python", "src/ui/gradio_ui.py"]
    volumes:
      - ./src:/app/src
      - ./ui:/app/src/ui
      - ./requirements.txt:/app/requirements.txt
